#!/bin/bash

usage() {
    echo "用法: $0 [build|run|remove]"
    echo "命令:"
    echo "  build   - 構建 nginx 映像"
    echo "  run     - 運行 nginx 容器"
    echo "  remove  - 停止並刪除容器"
    exit 1
}

if [ $# -eq 0 ]; then
    usage
fi

case "$1" in
    build)
	docker build -t mynginx-alpine .
	docker image prune -f
        ;;
    run)
	docker run -d -p 80:80 --name mynginx --restart unless-stopped mynginx-alpine
	docker exec -it mynginx sh
        ;;
    remove)
    	docker rm -f mynginx
        ;;
    *)
        echo "無效的命令: $1"
        usage
        ;;
esac
